# Generated by Django 4.2.7 on 2024-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_etiquette_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10),
        ),
    ]
