# Generated by Django 3.2.23 on 2024-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfApp', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='score',
        ),
        migrations.AddField(
            model_name='participant',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
