# Generated by Django 3.2.23 on 2024-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfApp', '0005_alter_participant_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='participant',
            name='kana_name',
            field=models.CharField(default='', max_length=100, verbose_name='氏名カナ'),
        ),
        migrations.AddField(
            model_name='participant',
            name='transportation',
            field=models.CharField(choices=[('Y', 'あり'), ('N', 'なし')], default='N', max_length=2, verbose_name='移動手段'),
        ),
    ]
