# Generated by Django 3.2.23 on 2024-03-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GolfApp', '0006_auto_20240326_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to='GolfApp.Participant')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='GolfApp.groupingresult')),
            ],
        ),
    ]
