# Generated by Django 3.2.23 on 2024-03-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfApp', '0007_group_groupingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='participant',
            name='building',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(default='', max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='participant',
            name='prefecture',
            field=models.CharField(default='', max_length=100, verbose_name='都道府県'),
        ),
    ]
